# Generated by Django 4.2 on 2023-05-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(default='random968991', max_length=255, unique=True),
        ),
    ]
