# Generated by Django 4.2 on 2023-05-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_interest_alter_user_username_remove_user_interests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interests',
            new_name='interest',
        ),
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(default='random625764', max_length=255, unique=True),
        ),
    ]
