# Generated by Django 4.2 on 2023-05-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_interests_user_interest_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(default='random842594', max_length=255, unique=True),
        ),
    ]
